site_name: 2026.8.15 TO Lsh
site_description: 一个用 MkDocs 搭建的个人网站

theme:
  name: material
  language: zh
  palette:
    scheme: default
    primary: white
  features:
    - header.autohide
    - navigation.top
    - navigation.footer

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: true
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/home.js

nav:
  - 主页: index.md
  - 致好友寄语: message/to_friend.md
